# Generated by Django 3.2.5 on 2021-08-14 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads')),
                ('title', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DishChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DishType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('title', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='uploads')),
                ('type', models.CharField(choices=[('v', 'vegan'), ('m', 'meat')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('number', models.SmallAutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False)),
                ('dishes', models.ManyToManyField(related_name='Orders', to='mainApp.Dish')),
            ],
        ),
        migrations.AddField(
            model_name='dish',
            name='changes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Dishes', to='mainApp.dishchange'),
        ),
        migrations.AddField(
            model_name='dish',
            name='ingredients',
            field=models.ManyToManyField(related_name='Dishes', to='mainApp.Ingredient'),
        ),
        migrations.AddField(
            model_name='dish',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Dishes', to='mainApp.dishtype'),
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('sub_title', models.CharField(max_length=250)),
                ('comment', models.TextField()),
                ('percent', models.PositiveIntegerField()),
                ('promo_code', models.CharField(max_length=20)),
                ('start_date', models.DateTimeField()),
                ('stop_date', models.DateTimeField()),
                ('dishes', models.ManyToManyField(related_name='Deals', to='mainApp.Dish')),
            ],
        ),
    ]
