# Generated by Django 3.2.6 on 2021-08-16 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_dish_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='first_name',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dish',
            name='changes',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Dish', to='mainApp.dishchange'),
        ),
    ]
