# Generated by Django 3.2.6 on 2021-08-16 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_auto_20210817_0219'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='mainApp.dish')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='mainApp.order')),
                ('remove_ingredients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.ingredient')),
            ],
        ),
    ]
