# Generated by Django 3.2.6 on 2021-08-17 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_alter_ordereddish_remove_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='dishes',
        ),
        migrations.RemoveField(
            model_name='ordereddish',
            name='remove_ingredients',
        ),
        migrations.AddField(
            model_name='ordereddish',
            name='remove_ingredients',
            field=models.ManyToManyField(null=True, to='mainApp.Ingredient'),
        ),
    ]
