# Generated by Django 3.2.6 on 2021-08-18 23:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainApp', '0006_auto_20210817_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ordereddish',
            name='remove_ingredients',
            field=models.ManyToManyField(null=True, related_name='OrderedDishes', to='mainApp.Ingredient'),
        ),
    ]
