# Generated by Django 3.2.6 on 2021-08-19 09:33

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('mainApp', '0008_myuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordereddish',
            name='remove_ingredients',
            field=models.ManyToManyField(blank=True, null=True, related_name='OrderedDishes', to='mainApp.Ingredient'),
        ),
        migrations.DeleteModel(
            name='MyUser',
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
